#!/usr/bin/env bash

rank=${OMPI_COMM_WORLD_LOCAL_RANK}
size=${OMPI_COMM_WORLD_LOCAL_SIZE}
case ${size} in
4)
  export UCX_NET_DEVICES=mlx5_${rank}:1
  export UCX_MAX_RNDV_LANES=1
  ;;
1)
  export UCX_NET_DEVICES=mlx5_0:1,mlx5_1:1,mlx5_2:1,mlx5_3:1
  export UCX_MAX_RNDV_LANES=4
  ;;
*)
  echo "invalid proc ${size} per node!"
  exit 1
  ;;
esac

export OMPI_MCA_btl=^vader,openib
  export OMPI_MCA_coll_hcoll_enable=0
export OMPI_MCA_pml=ucx
  export UCX_TLS=shm,rc_x
  export UCX_IB_PCI_BW=${UCX_NET_DEVICES//:1/:50Gbps}
  export UCX_IB_ADDR_TYPE=ib_global
  export UCX_IB_GID_INDEX=auto
export UCX_MAX_EAGER_LANES=1
export UCX_RNDV_SCHEME=get_zcopy
  export UCX_RNDV_THRESH=1023b
export UCX_WARN_UNUSED_ENV_VARS=n
  export UCX_LOG_LEVEL=FATAL

UCX_PATH=/opt/hpc/software/mpi/ucx_without_rocm
OMPI_PATH=/opt/hpc/software/mpi/hpcx/v2.4.0/ompi
export LD_LIBRARY_PATH=${PWD}:${UCX_PATH}/lib:${OMPI_PATH}/lib:${LD_LIBRARY_PATH}
numactl --cpunodebind=${rank} --membind=${rank} taskset -c $(($((rank*8))+7))\
  ${PWD}/mpiGraph $((4194304/$size)) 128 64
